import { useEffect, useMemo, useState } from "react";
import { invoke } from "@tauri-apps/api/core";
import { open } from "@tauri-apps/plugin-dialog";
import { Archive, BarChart3, FolderOpen, Library, RefreshCw, Settings as SettingsIcon, Tags } from "lucide-react";
import type { Pack, ScanResult, Settings } from "./types";

const BANKS = [..."ABCDEFGH"];
const views = [{id:"banks",label:"Banks",icon:Library},{id:"packs",label:"Sound Packs",icon:Archive},{id:"tags",label:"Tags",icon:Tags},{id:"stats",label:"Statistics",icon:BarChart3},{id:"settings",label:"Settings",icon:SettingsIcon}] as const;

export default function App() {
  const [view,setView]=useState("banks"); const [bank,setBank]=useState("A");
  const [settings,setSettings]=useState<Settings>({banksPath:null,packsPath:null});
  const [data,setData]=useState<ScanResult|null>(null); const [busy,setBusy]=useState(false); const [message,setMessage]=useState("Ready"); const [selectedPack,setSelectedPack]=useState<Pack|null>(null); const [emptyOnly,setEmptyOnly]=useState(false);
  const ready=!!settings.banksPath&&!!settings.packsPath;
  useEffect(()=>{ invoke<Settings>("load_settings").then(s=>{setSettings(s); if(!s.banksPath||!s.packsPath)setView("settings");}).catch(e=>setMessage(String(e))); },[]);
  useEffect(()=>{ if(ready&&!data) scan(); },[ready]);
  async function scan(){ if(!ready)return; setBusy(true);setMessage("Scanning presets and sound packs…");try{const result=await invoke<ScanResult>("scan_library",{banksPath:settings.banksPath,packsPath:settings.packsPath});setData(result);setMessage(`Scan complete · ${Object.values(result.banks).flat().length} presets · ${result.packs.length} sound packs`);}catch(e){setMessage(`Scan failed: ${e}`)}finally{setBusy(false)}}
  async function choose(kind:"banks"|"packs"){const path=await open({directory:true,multiple:false,title:kind==="banks"?"Select folder containing banks A–H":"Select sound packs folder"});if(!path)return;const next={...settings,[kind==="banks"?"banksPath":"packsPath"]:path as string};await invoke("save_settings",{settings:next});setSettings(next);setData(null);}
  const tagCounts=useMemo(()=>{const m:Record<string,number>={};Object.values(data?.banks??{}).flat().forEach(p=>p.tags.forEach(t=>m[t]=(m[t]??0)+1));return Object.entries(m).sort((a,b)=>b[1]-a[1]||a[0].localeCompare(b[0]));},[data]);
  return <div className="min-h-screen">
    <header className="border-b border-white/10 bg-[#087f8c] px-6 py-5"><h1 className="text-xl font-bold">Digitone Presets</h1><p className="text-sm text-white/70">Browse banks, sound packs, tags, and duplicates</p></header>
    <div className="flex min-h-[calc(100vh-91px)]"><aside className="w-60 border-r border-white/10 bg-[#0b1c15] p-4"><nav className="space-y-2">{views.map(({id,label,icon:Icon})=><button key={id} disabled={!ready&&id!=="settings"} onClick={()=>setView(id)} className={`nav w-full ${view===id?"nav-active":""}`}><Icon size={18}/>{label}</button>)}</nav><button onClick={scan} disabled={!ready||busy} className="nav mt-8 w-full"><RefreshCw size={18} className={busy?"animate-spin":""}/>Scan again</button></aside>
      <main className="min-w-0 flex-1 p-6">
        {view==="banks"&&<><div className="mb-5 flex gap-2">{BANKS.map(b=><button onClick={()=>setBank(b)} className={`h-10 w-12 rounded-xl font-bold ${bank===b?"bg-accent text-ink":"bg-white/5 text-slate-400"}`}>{b}</button>)}</div><Table headers={["Slot","Preset","Sound pack(s)","Tags","Duplicates"]}>{(data?.banks[bank]??[]).map(p=><tr key={p.slot} className={p.duplicateLocations.length?"text-red-300":""}><td>{String(p.slot).padStart(3,"0")}</td><td className="font-medium">{p.name}</td><td>{[...p.exactPacks,...p.nameOnlyPacks].join(", ")||"—"}</td><td>{p.tags.join(", ")||"—"}</td><td>{p.duplicateLocations.join(", ")||"—"}</td></tr>)}</Table></>}
        {view==="packs"&&<><label className="mb-4 flex items-center gap-3 muted"><input type="checkbox" checked={emptyOnly} onChange={e=>setEmptyOnly(e.target.checked)}/> Show only packs with no matches</label><div className="grid gap-5 xl:grid-cols-[1fr_1fr]"><Table headers={["Sound pack","Found","Total"]}>{(data?.packs??[]).filter(p=>!emptyOnly||p.found===0).map(p=><tr key={p.name} onClick={()=>setSelectedPack(p)} className="cursor-pointer hover:bg-white/5"><td>{p.name}</td><td>{p.found}</td><td>{p.total}</td></tr>)}</Table><div className="card p-6">{selectedPack?<><h2 className="text-xl font-bold">{selectedPack.name}</h2><p className="mt-2 muted">{selectedPack.found} of {selectedPack.total} found</p><h3 className="mt-6 font-semibold text-mint">Tags</h3><p className="mt-2 muted">{Object.entries(selectedPack.tags).sort((a,b)=>b[1]-a[1]).map(([t,n])=>`${t} (${n})`).join(", ")||"—"}</p><h3 className="mt-6 font-semibold text-mint">Bank positions</h3>{selectedPack.matches.map(m=><p className="mt-2 text-sm">{m.location} · {m.name}</p>)}</>:<p className="muted">Select a sound pack to view details.</p>}</div></div></>}
        {view==="tags"&&<Table headers={["Tag","Presets"]}>{tagCounts.map(([tag,n])=><tr key={tag}><td>{tag}</td><td>{n}</td></tr>)}</Table>}
        {view==="stats"&&<Table headers={["Bank","Presets","Capacity","Status"]}>{BANKS.map(b=>{const n=data?.banks[b]?.length??0;return <tr key={b}><td>Bank {b}</td><td>{n}</td><td>256</td><td className={n>256?"text-red-300":n===256?"text-amber-300":"text-mint"}>{n>256?"Over capacity":n===256?"Full":"Available"}</td></tr>})}</Table>}
        {view==="settings"&&<div className="card max-w-4xl p-6"><h2 className="text-xl font-bold">Collection folders</h2><FolderRow label="Banks A–H" value={settings.banksPath} onClick={()=>choose("banks")}/><FolderRow label="Sound packs" value={settings.packsPath} onClick={()=>choose("packs")}/><p className="mt-5 muted">Folder paths are stored locally in the application settings.</p></div>}
      </main></div><footer className="fixed bottom-0 left-60 right-0 border-t border-white/10 bg-[#0b1c15] px-6 py-2 text-xs text-mint">{message}</footer>
  </div>
}
function Table({headers,children}:{headers:string[],children:React.ReactNode}){return <div className="card max-h-[calc(100vh-190px)] overflow-auto"><table className="w-full border-collapse"><thead><tr>{headers.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{children}</tbody></table></div>}
function FolderRow({label,value,onClick}:{label:string,value:string|null,onClick:()=>void}){return <div className="mt-5 grid items-center gap-4 md:grid-cols-[130px_1fr_auto]"><span className="font-semibold">{label}</span><span className="truncate rounded-xl border border-line bg-black/10 px-4 py-3 text-sm text-slate-300">{value||"Not set"}</span><button className="btn flex items-center gap-2" onClick={onClick}><FolderOpen size={17}/>Browse…</button></div>}
